# Generated by Django 5.2.3 on 2025-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('nombre', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=25)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estado_salud', models.CharField(choices=[('Saludable', 'Saludable'), ('En tratamiento', 'En tratamiento')], max_length=25)),
                ('tamaño', models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=2)),
                ('vacunado', models.BooleanField(default=False)),
                ('estado_adopcion', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=25)),
                ('temperamento', models.CharField(choices=[('Cariñoso', 'Cariñoso'), ('Timido', 'Tímido'), ('Juguetón', 'Juguetón'), ('Agresivo', 'Agresivo')], max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telf', models.CharField(max_length=15)),
                ('preferencias', models.CharField(choices=[('Golden Retriever', 'Golden Retriever'), ('Labrador', 'Labrador'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Callejero', 'Callejero'), ('Husky Siberiano', 'Husky Siberiano'), ('Pequines', 'Pequinés')], max_length=25)),
                ('historial_adopciones', models.ManyToManyField(blank=True, to='AdopcionApp.perro')),
            ],
        ),
    ]
