# Generated by Django 5.2.3 on 2025-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Joven', 'Joven'), ('Adulto', 'Adulto'), ('Viejito', 'Viejito')], max_length=10),
        ),
    ]
