# Generated by Django 5.2.3 on 2025-06-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0002_alter_perro_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_adopcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdopcionApp.usuarioadoptante')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdopcionApp.perro')),
            ],
        ),
    ]
