# Generated by Django 5.2.3 on 2025-06-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0003_adopcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='fecha_inicio',
        ),
    ]
