# Generated by Django 5.2.3 on 2025-06-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0004_remove_adopcion_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadoptante',
            name='preferencias',
        ),
        migrations.AddField(
            model_name='usuarioadoptante',
            name='pref_edad',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Joven', 'Joven'), ('Adulto', 'Adulto'), ('Viejito', 'Viejito')], default='Adulto', max_length=10),
        ),
        migrations.AddField(
            model_name='usuarioadoptante',
            name='pref_raza',
            field=models.CharField(choices=[('Golden Retriever', 'Golden Retriever'), ('Labrador', 'Labrador'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Callejero', 'Callejero'), ('Husky Siberiano', 'Husky Siberiano'), ('Pequines', 'Pequinés'), ('Pitbull', 'Pitbull'), ('Pastor Alemán', 'Pastor Alemán'), ('Otro', 'Otro')], default='Labrador', max_length=25),
        ),
        migrations.AddField(
            model_name='usuarioadoptante',
            name='pref_tamaño',
            field=models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande')], default='Pequeño', max_length=2),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('Golden Retriever', 'Golden Retriever'), ('Labrador', 'Labrador'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Callejero', 'Callejero'), ('Husky Siberiano', 'Husky Siberiano'), ('Pequines', 'Pequinés'), ('Pitbull', 'Pitbull'), ('Pastor Alemán', 'Pastor Alemán'), ('Otro', 'Otro')], max_length=25),
        ),
    ]
