# Generated by Django 5.2.3 on 2025-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0005_remove_usuarioadoptante_preferencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadoptante',
            name='pref_sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('xx', 'Cualquiera')], default='Cualquiera', max_length=6),
        ),
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Joven', 'Joven'), ('Adulto', 'Adulto'), ('Viejito', 'Viejito'), ('xx', 'Cualquiera')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('Golden Retriever', 'Golden Retriever'), ('Labrador', 'Labrador'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Callejero', 'Callejero'), ('Husky Siberiano', 'Husky Siberiano'), ('Pequines', 'Pequinés'), ('Pitbull', 'Pitbull'), ('Pastor Alemán', 'Pastor Alemán'), ('Otro', 'Otro'), ('xx', 'Cualquiera')], max_length=25),
        ),
        migrations.AlterField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('xx', 'Cualquiera')], max_length=6),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('xx', 'Cualquiera')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_edad',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Joven', 'Joven'), ('Adulto', 'Adulto'), ('Viejito', 'Viejito'), ('xx', 'Cualquiera')], default='Cualquiera', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_raza',
            field=models.CharField(choices=[('Golden Retriever', 'Golden Retriever'), ('Labrador', 'Labrador'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Callejero', 'Callejero'), ('Husky Siberiano', 'Husky Siberiano'), ('Pequines', 'Pequinés'), ('Pitbull', 'Pitbull'), ('Pastor Alemán', 'Pastor Alemán'), ('Otro', 'Otro'), ('xx', 'Cualquiera')], default='Cualquiera', max_length=25),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_tamaño',
            field=models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('xx', 'Cualquiera')], default='Cualquiera', max_length=2),
        ),
    ]
